-- SurgiLink Master Database Schema
-- Last Updated: 2026-02-19

-- 1. Patients Table
CREATE TABLE IF NOT EXISTS public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    operation TEXT,
    date DATE,
    birth_date DATE,
    phone TEXT,
    email TEXT,
    surgeon_name TEXT DEFAULT 'Christophe DESOUCHES',
    surgery_time TEXT DEFAULT '07:30',
    stay_type TEXT DEFAULT 'Ambulatoire',
    status TEXT DEFAULT 'pending',
    progress INTEGER DEFAULT 0,
    days_until TEXT DEFAULT 'J-0',
    clinic_name TEXT,
    clinic_image_url TEXT,
    appointment_datetime TIMESTAMPTZ,
    score_status TEXT DEFAULT 'SAIN',
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

-- 2. Medical History Table
CREATE TABLE IF NOT EXISTS public.medical_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL DEFAULT 'intervention' CHECK (category IN ('intervention', 'sms')),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE public.medical_history ENABLE ROW LEVEL SECURITY;

-- 3. Patient Documents Table
CREATE TABLE IF NOT EXISTS public.patient_documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    size TEXT,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE public.patient_documents ENABLE ROW LEVEL SECURITY;

-- 4. Pathway Responses Table (Ambulatory Pathway)
CREATE TABLE IF NOT EXISTS public.pathway_responses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    screen TEXT NOT NULL CHECK (screen IN ('J7', 'J2', 'J1', 'J2_Satisfaction')),
    item_id TEXT NOT NULL,
    response JSONB NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    UNIQUE(patient_id, screen, item_id)
);

-- Enable RLS
ALTER TABLE public.pathway_responses ENABLE ROW LEVEL SECURITY;

-- 5. SMS Logs Table
CREATE TABLE IF NOT EXISTS public.sms_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    template_key TEXT NOT NULL,
    linked_item_id TEXT,
    screen TEXT,
    phone_number TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('queued', 'sent', 'failed', 'delivered')) DEFAULT 'queued',
    provider_message_id TEXT,
    error_message TEXT,
    sent_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE public.sms_logs ENABLE ROW LEVEL SECURITY;

-- 6. Reminder Queue Table
CREATE TABLE IF NOT EXISTS public.reminder_queue (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    screen TEXT NOT NULL,
    item_id TEXT,
    scheduled_for TIMESTAMPTZ NOT NULL,
    reminder_type TEXT NOT NULL CHECK (reminder_type IN ('auto_time', 'auto_state', 'manual')),
    template_key TEXT NOT NULL,
    processed_at TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed', 'cancelled')) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE public.reminder_queue ENABLE ROW LEVEL SECURITY;

-- ============================================
-- POLICIES
-- ============================================

-- Patients
CREATE POLICY "Users can view their own patients" ON public.patients FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert clinical data" ON public.patients FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own patients" ON public.patients FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- Medical History
CREATE POLICY "Users can view their patients' history" ON public.medical_history FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert history" ON public.medical_history FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their patients' history" ON public.medical_history FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their patients' history" ON public.medical_history FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Documents
CREATE POLICY "Users can view their own patient documents" ON public.patient_documents FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert patient documents" ON public.patient_documents FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own patient documents" ON public.patient_documents FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Pathway Responses
CREATE POLICY "Users can view their own pathway responses" ON public.pathway_responses FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own pathway responses" ON public.pathway_responses FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own pathway responses" ON public.pathway_responses FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- SMS Logs
CREATE POLICY "Users can view their own sms logs" ON public.sms_logs FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert sms logs" ON public.sms_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own sms logs" ON public.sms_logs FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- Reminder Queue
CREATE POLICY "Users can view their own reminders" ON public.reminder_queue FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert reminders" ON public.reminder_queue FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own reminders" ON public.reminder_queue FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS idx_pathway_responses_patient_screen ON public.pathway_responses(patient_id, screen);
CREATE INDEX IF NOT EXISTS idx_sms_logs_patient ON public.sms_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_sms_logs_status ON public.sms_logs(status);
CREATE INDEX IF NOT EXISTS idx_reminder_queue_scheduled ON public.reminder_queue(scheduled_for, status);
CREATE INDEX IF NOT EXISTS idx_reminder_queue_patient ON public.reminder_queue(patient_id);
CREATE INDEX IF NOT EXISTS idx_medical_history_patient ON public.medical_history(patient_id);
CREATE INDEX IF NOT EXISTS idx_medical_history_category ON public.medical_history(patient_id, category);
CREATE INDEX IF NOT EXISTS idx_patient_documents_patient ON public.patient_documents(patient_id);
