-- Create the patients table
CREATE TABLE IF NOT EXISTS public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    operation TEXT,
    date DATE,
    phone TEXT,
    email TEXT,
    status TEXT DEFAULT 'pending',
    progress INTEGER DEFAULT 0,
    days_until TEXT DEFAULT 'J-0',
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

-- Create policy to allow authenticated users to see only their own patients
CREATE POLICY "Users can view their own patients" 
ON public.patients FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

-- Create policy to allow authenticated users to insert their own patients
CREATE POLICY "Users can insert clinical data" 
ON public.patients FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- Create policy to allow authenticated users to update their own patients
CREATE POLICY "Users can update their own patients" 
ON public.patients FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id);

-- ============================================
-- AMBULATORY PATHWAY MODULE TABLES
-- ============================================

-- Create pathway_responses table
CREATE TABLE IF NOT EXISTS public.pathway_responses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    screen TEXT NOT NULL CHECK (screen IN ('J7', 'J2', 'J1')),
    item_id TEXT NOT NULL,
    response JSONB NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    UNIQUE(patient_id, screen, item_id)
);

-- Create sms_logs table
CREATE TABLE IF NOT EXISTS public.sms_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    template_key TEXT NOT NULL,
    linked_item_id TEXT,
    screen TEXT,
    phone_number TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('queued', 'sent', 'failed', 'delivered')) DEFAULT 'queued',
    provider_message_id TEXT,
    error_message TEXT,
    sent_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Create reminder_queue table
CREATE TABLE IF NOT EXISTS public.reminder_queue (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    screen TEXT NOT NULL,
    item_id TEXT,
    scheduled_for TIMESTAMPTZ NOT NULL,
    reminder_type TEXT NOT NULL CHECK (reminder_type IN ('auto_time', 'auto_state', 'manual')),
    template_key TEXT NOT NULL,
    processed_at TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed', 'cancelled')) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable Row Level Security on new tables
ALTER TABLE public.pathway_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sms_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminder_queue ENABLE ROW LEVEL SECURITY;

-- Policies for pathway_responses
CREATE POLICY "Users can view their own pathway responses" 
ON public.pathway_responses FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own pathway responses" 
ON public.pathway_responses FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own pathway responses" 
ON public.pathway_responses FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id);

-- Policies for sms_logs
CREATE POLICY "Users can view their own sms logs" 
ON public.sms_logs FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert sms logs" 
ON public.sms_logs FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own sms logs" 
ON public.sms_logs FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id);

-- Policies for reminder_queue
CREATE POLICY "Users can view their own reminders" 
ON public.reminder_queue FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert reminders" 
ON public.reminder_queue FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reminders" 
ON public.reminder_queue FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_pathway_responses_patient_screen ON public.pathway_responses(patient_id, screen);
CREATE INDEX IF NOT EXISTS idx_sms_logs_patient ON public.sms_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_sms_logs_status ON public.sms_logs(status);
CREATE INDEX IF NOT EXISTS idx_reminder_queue_scheduled ON public.reminder_queue(scheduled_for, status);
CREATE INDEX IF NOT EXISTS idx_reminder_queue_patient ON public.reminder_queue(patient_id);
