-- Add birth_date column to patients table
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS birth_date DATE;

-- Create medical_history table
CREATE TABLE IF NOT EXISTS public.medical_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE public.medical_history ENABLE ROW LEVEL SECURITY;

-- RLS Policies for medical_history
CREATE POLICY "Users can view their patients' history" 
ON public.medical_history FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert history" 
ON public.medical_history FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their patients' history" 
ON public.medical_history FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their patients' history" 
ON public.medical_history FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_medical_history_patient ON public.medical_history(patient_id);
