-- Migration: Create custom_questions table for punctual clinical questions
-- Purpose: Allow practitioners to add specific questions for individual patients

CREATE TABLE IF NOT EXISTS public.custom_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    response TEXT,
    answered_at TIMESTAMPTZ,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE public.custom_questions ENABLE ROW LEVEL SECURITY;

-- 1. Policy to allow AUTHENTICATED users (staff) to manage all custom questions
CREATE POLICY "Allow authenticated users to manage custom questions"
ON public.custom_questions
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- 2. Policy to allow ANON users (patient portal) to READ their own custom questions
CREATE POLICY "Allow patient portal to read own custom questions"
ON public.custom_questions
FOR SELECT
TO anon
USING (has_valid_patient_token(patient_id));

-- 3. Policy to allow ANON users (patient portal) to UPDATE their own custom questions (answer them)
CREATE POLICY "Allow patient portal to update own custom questions"
ON public.custom_questions
FOR UPDATE
TO anon
USING (has_valid_patient_token(patient_id))
WITH CHECK (has_valid_patient_token(patient_id));

-- Grant permissions
GRANT ALL ON public.custom_questions TO authenticated;
GRANT SELECT, UPDATE ON public.custom_questions TO anon;

-- Comment
COMMENT ON TABLE public.custom_questions IS 'Stores punctual/one-off questions added by practitioners for specific patients';
