-- Adding missing columns to patients table
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS surgeon_name TEXT DEFAULT 'Christophe DESOUCHES';
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS surgery_time TEXT DEFAULT '07:30';
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS stay_type TEXT DEFAULT 'Ambulatoire';
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS clinic_name TEXT;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS clinic_image_url TEXT;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS appointment_datetime TIMESTAMPTZ;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS score_status TEXT DEFAULT 'SAIN';

-- Create medical_history table
CREATE TABLE IF NOT EXISTS public.medical_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL DEFAULT 'intervention' CHECK (category IN ('intervention', 'sms')),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);
ALTER TABLE public.medical_history ENABLE ROW LEVEL SECURITY;

-- Create patient_documents table
CREATE TABLE IF NOT EXISTS public.patient_documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    size TEXT,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);
ALTER TABLE public.patient_documents ENABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
